In [24]:
# python libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import scipy.stats as stats
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model
from tensorflow.keras.utils import plot_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [3]:
data = pd.read_csv(r'D:\Downloads\iris.csv')
data.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [45]:
X = data.iloc[:,0:4]
y = data.iloc[:,4]


In [46]:
encoder = LabelEncoder()
encoder.fit(y)
y_new = encoder.transform(y)
y_new

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [61]:

yy_new = tf.one_hot(tf.constant(y_new),depth = 3)
yy_new  = yy_new.numpy()
yy_new


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [64]:
X_train,X_test,y_train,y_test = train_test_split(X,yy_new,test_size = 0.2)

In [65]:
tf.random.set_seed(42)
X_train_new = tf.constant(X_train, dtype = tf.float32)
X_test_new = tf.constant(X_test, dtype = tf.float32)
y_train_new = tf.constant(y_train, dtype = tf.float32)
y_test_new = tf.constant(y_test, dtype = tf.float32)
y_train_new

<tf.Tensor: shape=(120, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
     

In [71]:
#define the model
layer1 = Input(shape = (4,))
layer2 = Dense(10, activation = 'relu')(layer1)
output = Dense(3,activation = 'softmax')(layer2)
our_model = Model(inputs = layer1, outputs = output)

In [72]:
#compile the model 
our_model.compile(loss = 'categorical_crossentropy',
                 optimizer = 'Adam',
                 metrics = ['accuracy'])

In [74]:
#fit the model
our_model.fit(X_train_new, y_train_new, epochs = 60)

Epoch 1/60
4/4 [==============================] - 0s 998us/step - loss: 0.5274 - accuracy: 0.6750
Epoch 2/60
4/4 [==============================] - 0s 2ms/step - loss: 0.5251 - accuracy: 0.6750
Epoch 3/60
4/4 [==============================] - 0s 1ms/step - loss: 0.5233 - accuracy: 0.6750
Epoch 4/60
4/4 [==============================] - 0s 1ms/step - loss: 0.5215 - accuracy: 0.6750
Epoch 5/60
4/4 [==============================] - 0s 1ms/step - loss: 0.5196 - accuracy: 0.6750
Epoch 6/60
4/4 [==============================] - 0s 997us/step - loss: 0.5178 - accuracy: 0.6750
Epoch 7/60
4/4 [==============================] - 0s 2ms/step - loss: 0.5161 - accuracy: 0.6750
Epoch 8/60
4/4 [==============================] - 0s 2ms/step - loss: 0.5145 - accuracy: 0.6750
Epoch 9/60
4/4 [==============================] - 0s 1ms/step - loss: 0.5127 - accuracy: 0.6750
Epoch 10/60
4/4 [==============================] - 0s 2ms/step - loss: 0.5110 - accuracy: 0.6750
Epoch 11/60
4/4 [==================

In [75]:
our_model.predict(X_test_new)

array([[0.01276211, 0.43944448, 0.5477934 ],
       [0.9608201 , 0.01094857, 0.02823139],
       [0.0081041 , 0.42076337, 0.5711325 ],
       [0.02727004, 0.4643695 , 0.50836045],
       [0.9600751 , 0.01149505, 0.02842994],
       [0.96253335, 0.01117351, 0.02629313],
       [0.05135467, 0.4854415 , 0.46320385],
       [0.04153287, 0.47226554, 0.48620164],
       [0.00812725, 0.42019618, 0.57167655],
       [0.00478344, 0.39633155, 0.59888494],
       [0.04001155, 0.47701502, 0.4829735 ],
       [0.05222768, 0.48598543, 0.4617869 ],
       [0.00562767, 0.40277123, 0.59160113],
       [0.00997156, 0.4287176 , 0.56131077],
       [0.9739619 , 0.00643261, 0.01960559],
       [0.03140207, 0.47192279, 0.49667516],
       [0.01154408, 0.43514833, 0.5533076 ],
       [0.14940195, 0.40585628, 0.44474182],
       [0.0069264 , 0.41303456, 0.580039  ],
       [0.03467503, 0.4514098 , 0.5139152 ],
       [0.00884929, 0.42402005, 0.5671307 ],
       [0.9768506 , 0.00591798, 0.01723141],
       [0.

In [70]:
y_test_new

<tf.Tensor: shape=(30, 3), dtype=float32, numpy=
array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], dtype=float32)>